Terraform is an open-source infrastructure as code (IaC) tool that allows you to define and provision infrastructure resources across various cloud providers and other infrastructure platforms.

A Terraform script, written in HashiCorp Configuration Language (HCL), is a set of declarative statements that define the desired state of your infrastructure resources. It specifies the resources to be created, their configurations, and any dependencies between them.

You initialize a Terraform project by running the terraform init command in the project directory. It downloads the necessary provider plugins and sets up the working directory for Terraform.

How do you create a Terraform resource?

resource "aws_instance" "example" {
  ami           = "ami-0c94855ba95c71c99"
  instance_type = "t2.micro"
}


How do you plan and apply changes using Terraform?

    To plan changes without actually applying them, you run terraform plan command. It analyzes the Terraform script, compares the desired state with the current state, and generates an execution plan.
    To apply the changes and provision resources, you run terraform apply command. It executes the execution plan generated by the terraform plan command.

How do you manage Terraform state?

    Terraform state is managed using a state file that tracks the current state of the infrastructure resources. The state file is typically stored remotely or in a backend such as AWS S3 or HashiCorp Consul. You can configure the backend in the Terraform script or through CLI flags.

How do you destroy resources created by Terraform?

    To destroy resources created by Terraform, you run terraform destroy command. It reads the Terraform script, identifies the resources to destroy, and prompts for confirmation before performing the destruction.

How do you work with variables in Terraform?

    Terraform supports variables to parameterize your infrastructure configuration. You can define variables in the Terraform script or in separate variable files. Variables can be assigned default values or provided at runtime through CLI flags or environment variables.